name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Docker Build and Push
        run: |
          docker build -t young5097/edrink24-server:latest .
          docker push young5097/edrink24-server:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ec2-user@15.152.212.79 << 'EOF'
          docker pull young5097/edrink24-server:latest
          docker stop $(docker ps -q --filter ancestor=young5097/edrink24-server:latest)
          docker rm $(docker ps -a -q --filter ancestor=young5097/edrink24-server:latest)
          docker run -d -p 8090:8090 young5097/edrink24-server:latest
          EOF
